# Generated by Django 4.0.4 on 2022-05-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='insertdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='insertnewpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('diabetic', models.CharField(max_length=100)),
                ('bloodpressure', models.CharField(max_length=100)),
                ('heartdiseases', models.CharField(max_length=100)),
                ('surgery1', models.CharField(max_length=100)),
                ('surgery2', models.CharField(max_length=100)),
                ('surgery3', models.CharField(max_length=100)),
                ('prescriptions', models.CharField(max_length=300)),
                ('imgPath', models.CharField(max_length=100)),
                ('tumortype', models.CharField(max_length=100)),
                ('patientID', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='treatmentplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(max_length=100)),
                ('treatmentID', models.CharField(max_length=100)),
            ],
        ),
    ]
