# Generated by Django 4.0.4 on 2022-06-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='treatmentplan',
        ),
        migrations.RemoveField(
            model_name='insertnewpatient',
            name='surgery1',
        ),
        migrations.RemoveField(
            model_name='insertnewpatient',
            name='surgery2',
        ),
        migrations.RemoveField(
            model_name='insertnewpatient',
            name='surgery3',
        ),
        migrations.AddField(
            model_name='insertnewpatient',
            name='treatmentplan',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
